[build]
command = "rm -rf __obsidian __site __scripts && mkdir __obsidian && mkdir __scripts && mv .scripts/* __scripts && mv * __obsidian || true && git clone https://github.com/jackyzha0/quartz.git __site && __scripts/run.sh"
publish = "public"
