[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "Вперед к знаниям"
LANDING_DESCRIPTION = "Заметки нашей невероятной партии"
LANDING_PAGE = "Заметки"
LANDING_TITLE = ""
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/Wh1teF0x/dnd-notes"
SITE_TITLE = "Заметки"
SITE_TITLE_TAB = ""
SITE_URL = "https://campaing-notes.netlify.app/"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = ""
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = ""
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = ""
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = "y"
# (Optional, default blank) Additional footer content.
FOOTER = ""
# (Optional, default main) Root section name.
ROOT_SECTION_NAME = "main"
# (Optional) visjs graph options. Can remove if desired.
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
        		solver: "repulsion",
        	},
        }
        """