[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mkdir __site && mv .scripts/run.sh __site && mv * __obsidian || true && git clone https://github.com/jackyzha0/quartz.git __site && __site/run.sh"
publish = "public"
